pipeline {
    agent {
        label 'ecs2'
    }

    environment {
        EKS_CLUSTER = 'cdec-eks-dev'
        EKS_REGION = 'eu-north-1'
    }

    stages {

        stage('Checkout') {
            steps {
                git(
                    url: 'https://github.com/sakshigawale2112/cdec-alpha-app.git',
                    branch: 'main'
                )
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('application/backend/course-service') {
                    sh '''
                        docker build -t 503891328279.dkr.ecr.eu-north-1.amazonaws.com/cdec-alpha-course:latest .
                    '''
                }
            }
        }

        stage('Push to ECR') {
            steps {
                withCredentials([[
                    $class: 'AmazonWebServicesCredentialsBinding',
                    credentialsId: 'aws-creds',
                    accessKeyVariable: 'AWS_ACCESS_KEY_ID',
                    secretKeyVariable: 'AWS_SECRET_ACCESS_KEY'
                ]]) {
                    sh '''
                        aws ecr get-login-password --region eu-north-1 | \
                        docker login \
                        --username AWS \
                        --password-stdin 503891328279.dkr.ecr.eu-north-1.amazonaws.com

                        docker push 503891328279.dkr.ecr.eu-north-1.amazonaws.com/cdec-alpha-course:latest
                    '''
                }
            }
        }

        stage('Deploy to EKS') {
            steps {
                withCredentials([[
                    $class: 'AmazonWebServicesCredentialsBinding',
                    credentialsId: 'aws-creds',
                    accessKeyVariable: 'AWS_ACCESS_KEY_ID',
                    secretKeyVariable: 'AWS_SECRET_ACCESS_KEY'
                ]]) {
                    dir('application/backend/course-service') {
                        sh '''
                            aws eks update-kubeconfig \
                            --region eu-north-1 \
                            --name cdec-eks-dev

                            kubectl apply \
                            -f k8s/deployment.yml \
                            -n default

                            kubectl rollout restart \
                            deployment/course-service \
                            -n default

                            kubectl rollout status \
                            deployment/course-service \
                            -n default \
                            --timeout=300s
                        '''
                    }
                }
            }
        }
    }

    post {
        success {
            echo 'Course service deployed successfully!'
        }

        failure {
            echo 'Course service deployment failed.'
        }
    }
}
